---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: headline
  label: Überschrift
- type: textarea
  name: content
  label: Inhalt
  config:
    wysiwyg: true
    schema:
      format: markdown
pages:
- content/posts/second-post.md
